function setDarkTheme() {
    document.documentElement.style.setProperty('--cor-primaria', '#38184C');
    document.documentElement.style.setProperty('--cor-secundaria', '#9b0a59');
    document.documentElement.style.setProperty('--cor-texto', 'black');
    document.documentElement.style.setProperty('--cor-borda', '#CEF09D');
    document.documentElement.style.setProperty('--cor-transparente', '#4f6a93');
    document.documentElement.style.setProperty('--cor-branco', '#fff');
    document.documentElement.style.setProperty('--cor-verde', '#83E506');
    document.documentElement.style.setProperty('--cor-vermelho', '#FF0000');
    document.documentElement.style.setProperty('--cor-cinza', '#888');
    document.documentElement.style.setProperty('--cor-preto', '#000');
    document.documentElement.style.setProperty('--cor-cinzalight', '#ddd');
    document.documentElement.style.setProperty('--md-sys-color-primary', '#38184C');
    document.documentElement.style.setProperty('--md-sys-color-on-primary', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-primary-container', '#9b0a59');
    document.documentElement.style.setProperty('--md-sys-color-on-primary-container', 'black');
    document.documentElement.style.setProperty('--md-sys-color-background', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-on-background', 'black');
    document.documentElement.style.setProperty('--md-sys-color-surface', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-on-surface', 'black');
    document.documentElement.style.setProperty('--md-sys-color-error', '#FF0000');
    document.documentElement.style.setProperty('--md-sys-color-on-error', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-success', '#83E506');
    document.documentElement.style.setProperty('--md-sys-color-on-success', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-disabled', '#888');
    document.documentElement.style.setProperty('--md-sys-color-on-disabled', '#333333');
    document.documentElement.style.setProperty('--md-sys-color-border', '#CAE1F5');
    document.documentElement.style.setProperty('--md-sys-color-transparent', 'rgba(0, 0, 0, 0.1)');
    document.documentElement.style.setProperty('--md-sys-color-link', '#38184C');
    document.documentElement.style.setProperty('--md-sys-color-on-link', '#38184C');
}

function setLightTheme() {
    document.documentElement.style.setProperty('--cor-primaria', '#0067CF');
    document.documentElement.style.setProperty('--cor-secundaria', '#ceecff');
    document.documentElement.style.setProperty('--cor-texto', '#333333');
    document.documentElement.style.setProperty('--cor-borda', '#CAE1F5');
    document.documentElement.style.setProperty('--cor-transparente', 'rgba(0, 0, 0, 0.1)');
    document.documentElement.style.setProperty('--cor-branco', '#fff');
    document.documentElement.style.setProperty('--cor-verde', '#83E506');
    document.documentElement.style.setProperty('--cor-vermelho', '#FF0000');
    document.documentElement.style.setProperty('--cor-cinza', '#888');
    document.documentElement.style.setProperty('--cor-preto', '#000');
    document.documentElement.style.setProperty('--cor-cinzalight', '#ddd');
    document.documentElement.style.setProperty('--md-sys-color-primary', '#0067CF');
    document.documentElement.style.setProperty('--md-sys-color-on-primary', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-primary-container', '#ceecff');
    document.documentElement.style.setProperty('--md-sys-color-on-primary-container', '#333333');
    document.documentElement.style.setProperty('--md-sys-color-background', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-on-background', '#333333');
    document.documentElement.style.setProperty('--md-sys-color-surface', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-on-surface', '#333333');
    document.documentElement.style.setProperty('--md-sys-color-error', '#FF0000');
    document.documentElement.style.setProperty('--md-sys-color-on-error', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-success', '#83E506');
    document.documentElement.style.setProperty('--md-sys-color-on-success', '#fff');
    document.documentElement.style.setProperty('--md-sys-color-disabled', '#888');
    document.documentElement.style.setProperty('--md-sys-color-on-disabled', '#333333');
    document.documentElement.style.setProperty('--md-sys-color-border', '#CAE1F5');
    document.documentElement.style.setProperty('--md-sys-color-transparent', 'rgba(0, 0, 0, 0.1)');
    document.documentElement.style.setProperty('--md-sys-color-link', '#0067CF');
    document.documentElement.style.setProperty('--md-sys-color-on-link', '#0067CF');
}
